
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button suma;
	private global::Gtk.Button resta;
	private global::Gtk.Button multiplicacion;
	private global::Gtk.Entry entry1;
	private global::Gtk.Entry entry2;
	private global::Gtk.Entry entry3;
	private global::Gtk.Label resultado;
	private global::Gtk.Label numero2;
	private global::Gtk.Label numero1;
	private global::Gtk.Button divicion;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.suma = new global::Gtk.Button ();
		this.suma.CanFocus = true;
		this.suma.Name = "suma";
		this.suma.UseUnderline = true;
		this.suma.Label = global::Mono.Unix.Catalog.GetString ("Suma");
		this.fixed1.Add (this.suma);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.suma]));
		w1.X = 11;
		w1.Y = 228;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.resta = new global::Gtk.Button ();
		this.resta.CanFocus = true;
		this.resta.Name = "resta";
		this.resta.UseUnderline = true;
		this.resta.Label = global::Mono.Unix.Catalog.GetString ("Resta");
		this.fixed1.Add (this.resta);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.resta]));
		w2.X = 95;
		w2.Y = 227;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.multiplicacion = new global::Gtk.Button ();
		this.multiplicacion.CanFocus = true;
		this.multiplicacion.Name = "multiplicacion";
		this.multiplicacion.UseUnderline = true;
		this.multiplicacion.Label = global::Mono.Unix.Catalog.GetString ("Multiplicacion");
		this.fixed1.Add (this.multiplicacion);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.multiplicacion]));
		w3.X = 180;
		w3.Y = 227;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w4.X = 160;
		w4.Y = 29;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add (this.entry2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
		w5.X = 161;
		w5.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.fixed1.Add (this.entry3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry3]));
		w6.X = 161;
		w6.Y = 111;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.resultado = new global::Gtk.Label ();
		this.resultado.Name = "resultado";
		this.resultado.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.resultado);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.resultado]));
		w7.X = 85;
		w7.Y = 117;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero2 = new global::Gtk.Label ();
		this.numero2.Name = "numero2";
		this.numero2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero2");
		this.fixed1.Add (this.numero2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero2]));
		w8.X = 86;
		w8.Y = 72;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero1 = new global::Gtk.Label ();
		this.numero1.Name = "numero1";
		this.numero1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero1");
		this.fixed1.Add (this.numero1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero1]));
		w9.X = 88;
		w9.Y = 34;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.divicion = new global::Gtk.Button ();
		this.divicion.CanFocus = true;
		this.divicion.Name = "divicion";
		this.divicion.UseUnderline = true;
		this.divicion.Label = global::Mono.Unix.Catalog.GetString ("Divicion");
		this.fixed1.Add (this.divicion);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.divicion]));
		w10.X = 288;
		w10.Y = 226;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.suma.Clicked += new global::System.EventHandler (this.OnSumaClicked);
		this.multiplicacion.Clicked += new global::System.EventHandler (this.OnMultiplicacionClicked);
	}
}
